### ISSUE TITLE
Make this project not a fork

### ISSUE THREAD

**Issue by MatthewScholefield** [ofnode/of#17]
It's confusing when the official project is marked as a fork and makes you second guess whether you are on the right repo. As a suggestion, I'd recommend recreating the repo so that it isn't marked as a fork. Unfortunately, this would get rid of the 38 stars and people watching.

Let me know if you think this would be a good idea.

**Comment by avilleret** [comment]
another solution might be to ask aspeteRakete to transfer repo's ownership

for the record, the initial project was deleted and ownership has been automatically transfered to aspeteRakete while it was not up-to-date.
with the deletion of the original repo, we loose lots of data such as known bugs and wiki :-(

**Comment by MatthewScholefield** [comment]
@aspeteRakete Are you open to this?

**Comment by like-a-bause** [comment]
Hey Guys. Unfortunately I am not a member of ofnode and am not owner of this repository. I don't have access to the settings. I didn't even know that this repo still existed. As far as I remember the original author just deleted it without further notice and did not reply to any messages.

**Comment by avilleret** [comment]
hi @aspeteRakete the proposal was to move the ownership of your fork to this repo, so that this repo won't be marked as fork of yours. 
The original author deleted the whole ofnode organization without further notice (whilst he just say that he won't maintain it anymore), I recreate the ofnode organization with the clones I had on my computer

if you're interested in contributing, I can add you (both @MatthewScholefield and @aspeteRakete) as contributors and/or member organization member. This project definitely need you :-)

**Comment by like-a-bause** [comment]
Ok, I see. Sure thing. I just tried to transfer the ownership to ofnode but this is not possible because a repo under that name already exists in that organization. Any other ideas? Is deleting my fork a possibility?
The exact error message:
ofnode/of already exists and You don’t have the permission to create repositories on ofnode

**Comment by avilleret** [comment]
yes I think if you delete your fork then this one won't be marked as fork anymore
ofnode/of is up-to-date with all your commits

**Comment by like-a-bause** [comment]
Ok, I will delete my fork. Thanks for the invite, but currently I have no time resources to contribute. Keep up the spirit!

**Comment by like-a-bause** [comment]
Ok, so now this is a fork of https://github.com/kutabar/of
⚡️

**Comment by MatthewScholefield** [comment]
Awesome, I contacted GitHub support and they were really prompt in solving it :D.
