### ISSUE TITLE
all readme links are broken

### ISSUE THREAD

**Issue by jordiexvision** [ofnode/of#2]
Thank you for this. It looks like a promising initiative.
I would like to try to build on Windows and RPi but i can't find the right guide.

**Comment by avilleret** [comment]
you're right all the links are broken because original author disappear with all his work including those links
I restored as many things as I can put I don't have a backup for all things and especially for the Gist and wiki page.
Moreover I don't have a windows machine under the hand to test Windows build at the moment.
If you do have one, then I suggest you to try to build with clang, it has been reported to work on windows by the original author while MS Visual Studio build is broken and not supported anymore.

**Comment by avilleret** [comment]
closed with https://github.com/ofnode/of/commit/e5fc787cc4cf1587f27b44524274c911e363907f
