### ISSUE TITLE
ofxOpenCv : MIN / MAX not defined

### ISSUE THREAD

**Issue by avilleret** [ofnode/of#26]
adding ofxOpenCv addon leads to that error :

~~~~
/home/antoine/lib-src/ofnode/of/addons/ofxOpenCv/src/ofxCvImage.cpp:200:32: error: ‘MAX’ was not declared in this scope
         r3x1 = MAX( r1x1, r2x1 );
                                ^
/home/antoine/lib-src/ofnode/of/addons/ofxOpenCv/src/ofxCvImage.cpp:203:32: error: ‘MIN’ was not declared in this scope
         r3x2 = MIN( r1x2, r2x2 );
~~~~

when building on Ubuntu 15.04 with GCC

**Comment by procedural** [comment]
Weird C++ Time!

It's weird because on my system and Travis there are no such errors. Maybe because I test only on Clang?.. I could add GCC for testing, but honestly I couldn't care less about that compiler.

MIN and MAX are defined in ofConstants.h and it's there since 2008: https://github.com/openframeworks/openFrameworks/blob/55723ce/libs/openFrameworks/utils/ofConstants.h#L423-L429

Try to add `#include "ofConstants.h"` on top of `ofxCvImage.cpp` to workaround that.

**Comment by procedural** [comment]
I'm closing this issue since `ofConstants.h` is actually already included in `ofxCvImage.cpp` and here's how:

[ofxCvImage.cpp includes `#include "ofxCvImage.h"`](https://github.com/ofnode/of/blob/b3e2a5f/addons/ofxOpenCv/src/ofxCvImage.cpp#L2)
[ofxCvImage.h includes `#include "ofxCvConstants.h"`](https://github.com/ofnode/of/blob/b3e2a5f/addons/ofxOpenCv/src/ofxCvImage.h#L15)
[ofxCvConstants.h includes `#include "ofMain.h"`](https://github.com/ofnode/of/blob/b3e2a5f/addons/ofxOpenCv/src/ofxCvConstants.h#L12)
[ofMain.h includes `#include "ofConstants.h"`](https://github.com/ofnode/of/blob/b3e2a5f/src/openframeworks/ofMain.h#L5)
[And ofConstants has MIN and MAX defined](https://github.com/ofnode/of/blob/b3e2a5f/src/openframeworks/utils/ofConstants.h#L424-L430)

In your case, check addons or code you're using, most probably it undefines these macros somewhere.
