### ISSUE TITLE
missing GCC_HAS_REGEX definition ?

### ISSUE THREAD

**Issue by avilleret** [ofnode/of#28]
GCC_HAS_REGEX is not defined by default which lead to annoying reports on RPi (shader are printed to console :-/).

This is only used once here : https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofShader.cpp#L398

In openFrameworks vanilla build system it is defined in the common Makefile template : https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk#L134

So I guess we should implement something similar to define that too or ask of team to remove it. Who is still building with gcc 4.8 ?

**Comment by procedural** [comment]
GCC 4.8 is a standard version of Ubuntu 14.04 long term release, because of that we can't expect that people will add extra ppa for GCC 4.9... So to fix that properly we need to add definition if compiler's version is >= 4.9.

Thanks for pointing define in vanilla's Makefile, by the way! I rarely look there :)
